name: Release v2rayA zip files for homebrew-v2raya

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build v2rayA
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          export PATH="/home/linuxbrew/.linuxbrew/opt/node@18/bin:$PATH"
          brew install yarn node@18 go
          chmod +x build.sh
          ./build.sh
      - name: Release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            v2raya-x86_64-linux.zip
            v2raya-x86_64-linux.zip.sha256.txt
            v2raya-x86_64-macos.zip
            v2raya-x86_64-macos.zip.sha256.txt
            v2raya-aarch64-macos.zip
            v2raya-aarch64-macos.zip.sha256.txt
