name: Update v2raya.rb

on:
  workflow_dispatch:
  schedule:
    - cron: '20 */16 * * *'
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: Amadevus/pwsh-script@v2.0.1
      - name: Update v2raya.rb
        run: |
          cd /home/runner/work/homebrew-v2raya/homebrew-v2raya/
          ls -lh
          pwsh -c ./updater.ps1
      - name: Push
        uses: ad-m/github-push-action@master
        with:
#           github_url: https://github.com/v2raya/homebrew-v2raya
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
